/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LandingPrototypeRouteImport } from './routes/landing-prototype'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrototypeFooterRouteImport } from './routes/prototype-footer'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ProtectedDashboardRouteImport } from './routes/_protected/dashboard'
import { Route as ShareCodeRouteImport } from './routes/share.$code'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LandingPrototypeRoute = LandingPrototypeRouteImport.update({
  id: '/landing-prototype',
  path: '/landing-prototype',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeFooterRoute = PrototypeFooterRouteImport.update({
  id: '/prototype-footer',
  path: '/prototype-footer',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedDashboardRoute = ProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedRoute,
} as any)
const ShareCodeRoute = ShareCodeRouteImport.update({
  id: '/share/$code',
  path: '/share/$code',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing-prototype': typeof LandingPrototypeRoute
  '/login': typeof LoginRoute
  '/prototype-footer': typeof PrototypeFooterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/share/$code': typeof ShareCodeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing-prototype': typeof LandingPrototypeRoute
  '/login': typeof LoginRoute
  '/prototype-footer': typeof PrototypeFooterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/share/$code': typeof ShareCodeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/explore': typeof ExploreRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/landing-prototype': typeof LandingPrototypeRoute
  '/login': typeof LoginRoute
  '/prototype-footer': typeof PrototypeFooterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/share/$code': typeof ShareCodeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/explore'
    | '/forgot-password'
    | '/landing-prototype'
    | '/login'
    | '/prototype-footer'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/share/$code'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/explore'
    | '/forgot-password'
    | '/landing-prototype'
    | '/login'
    | '/prototype-footer'
    | '/reset-password'
    | '/signup'
    | '/dashboard'
    | '/share/$code'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/explore'
    | '/forgot-password'
    | '/landing-prototype'
    | '/login'
    | '/prototype-footer'
    | '/reset-password'
    | '/signup'
    | '/_protected/dashboard'
    | '/share/$code'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  ExploreRoute: typeof ExploreRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LandingPrototypeRoute: typeof LandingPrototypeRoute
  LoginRoute: typeof LoginRoute
  PrototypeFooterRoute: typeof PrototypeFooterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  ShareCodeRoute: typeof ShareCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/landing-prototype': {
      id: '/landing-prototype'
      path: '/landing-prototype'
      fullPath: '/landing-prototype'
      preLoaderRoute: typeof LandingPrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype-footer': {
      id: '/prototype-footer'
      path: '/prototype-footer'
      fullPath: '/prototype-footer'
      preLoaderRoute: typeof PrototypeFooterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/share/$code': {
      id: '/share/$code'
      path: '/share/$code'
      fullPath: '/share/$code'
      preLoaderRoute: typeof ShareCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ProtectedRouteChildren {
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedDashboardRoute: ProtectedDashboardRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  ExploreRoute: ExploreRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LandingPrototypeRoute: LandingPrototypeRoute,
  LoginRoute: LoginRoute,
  PrototypeFooterRoute: PrototypeFooterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  ShareCodeRoute: ShareCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
